-- =============================================================================
-- SEEDING PAKET SIMULASI TKA: MATEMATIKA (PAKET 01 & PAKET 02)
-- Berkas: migrations/005_seed_simulasi_tka_v6.sql
-- Sumber: docs/Simulasi TKA/Matematika/ (simulasitka_matematika_paket1.docx & paket2.docx)
-- Cakupan: 2 Paket Simulasi, 60 Soal Master, 240 Opsi Jawaban (LaTeX Math), 60 Pembahasan
-- =============================================================================

SET NAMES utf8mb4;
SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------------------------------
-- 1. PEMBENIHAN PAKET SIMULASI MATEMATIKA (SIMULATIONS)
-- -----------------------------------------------------------------------------
INSERT INTO `simulations` (`id`, `subject_id`, `title`, `package_code`, `duration_minutes`, `total_questions`, `passing_score`, `xp_reward`, `status`, `is_active`) VALUES
(1, 1, 'Simulasi TKA Matematika - Paket 01', 'MAT-SIM-01', 75, 30, 90.00, 500, 'ACTIVE', TRUE),
(2, 1, 'Simulasi TKA Matematika - Paket 02', 'MAT-SIM-02', 75, 30, 90.00, 500, 'ACTIVE', TRUE)
ON DUPLICATE KEY UPDATE `subject_id` = VALUES(`subject_id`), `title` = VALUES(`title`), `package_code` = VALUES(`package_code`), `duration_minutes` = VALUES(`duration_minutes`), `total_questions` = VALUES(`total_questions`), `passing_score` = VALUES(`passing_score`), `xp_reward` = VALUES(`xp_reward`), `status` = VALUES(`status`), `is_active` = VALUES(`is_active`);

-- -----------------------------------------------------------------------------
-- 2. PEMBENIHAN MASTER BANK SOAL SIMULASI MATEMATIKA (QUESTION_BANKS - 60 Butir Soal)
-- -----------------------------------------------------------------------------
INSERT INTO `question_banks` (`id`, `subject_id`, `sub_material_id`, `cognitive_level_id`, `stimulus_id`, `bank_type`, `question_format`, `question_text`, `question_image_url`, `is_active`) VALUES
(1, 1, 1, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Urutan bilangan dari yang terkecil ke terbesar yang tepat adalah ….', NULL, TRUE),
(2, 1, 1, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Nilai dari $|-8|$ adalah ….', NULL, TRUE),
(3, 1, 1, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Rina memiliki pita $3{,}6\\text{ m}$. Ia memakai $1{,}25\\text{ m}$ lalu membeli lagi $0{,}8\\text{ m}$. Pilih semua pernyataan yang benar.', NULL, TRUE),
(4, 1, 1, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Tanpa menghitung panjang, manakah yang lebih besar: $\\sqrt{50}$ atau $7$?', NULL, TRUE),
(5, 1, 1, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Nilai $n$ adalah bilangan bulat. Jika $-2 < \\frac{n}{3} < 1$, nilai $n$ yang mungkin adalah ….', NULL, TRUE),
(6, 1, 1, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Tiga pecahan berikut dibandingkan: $\\frac{5}{8}$, $\\frac{2}{3}$, dan $\\frac{3}{5}$. Pecahan terbesar adalah ….', NULL, TRUE),
(7, 1, 1, 3, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Sebuah bilangan real $x$ memenuhi $1 < x < 2$. Pilih semua kesimpulan yang pasti benar.', NULL, TRUE),
(8, 1, 2, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Doni membeli $3$ buku tulis seharga sama dan sebuah pensil $\\text{Rp}4.000$. Total belanja $\\text{Rp}25.000$. Pilih pernyataan yang benar.', NULL, TRUE),
(9, 1, 2, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua nilai $x$ yang memenuhi $2x - 1 \\le 5$.', NULL, TRUE),
(10, 1, 3, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Bentuk sederhana dari $4a + 3a - 2$ adalah ….', NULL, TRUE),
(11, 1, 3, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Harga $1$ roti adalah $x$ rupiah. Harga $4$ roti dan biaya kantong $\\text{Rp}2.000$ dinyatakan dengan ….', NULL, TRUE),
(12, 1, 4, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Jika $f(x) = 2x + 1$, maka $f(3)$ adalah ….', NULL, TRUE),
(13, 1, 4, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Sebuah mesin mengubah masukan $x$ menjadi keluaran $f(x) = 3x - 2$. Pilih semua pasangan masukan dan keluaran yang benar.', NULL, TRUE),
(14, 1, 5, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Mira menabung $\\text{Rp}5.000$ pada minggu pertama dan menambah tabungan mingguan sebesar $\\text{Rp}2.000$ setiap minggu. Pilih pernyataan benar untuk minggu ke-$4$.', NULL, TRUE),
(15, 1, 5, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Pola $2, 6, 18, 54, \\dots$ berlanjut dengan mengalikan setiap suku dengan $3$. Suku ke-$6$ adalah ….', NULL, TRUE),
(16, 1, 6, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Jumlah sudut dalam sebuah segitiga adalah ….', NULL, TRUE),
(17, 1, 6, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Segitiga memiliki sudut $48^\\circ$ dan $67^\\circ$. Pilih semua pernyataan benar.', NULL, TRUE),
(18, 1, 6, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah persegi memiliki panjang sisi $9\\text{ cm}$. Kelilingnya adalah ….', NULL, TRUE),
(19, 1, 7, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua transformasi yang mempertahankan bentuk dan ukuran bangun.', NULL, TRUE),
(20, 1, 7, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Segitiga dengan titik $A(1, 1)$, $B(3, 1)$, $C(1, 4)$ dicerminkan pada sumbu-$y$. Koordinat $A\'$ adalah ….', NULL, TRUE),
(21, 1, 8, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua konversi yang benar.', NULL, TRUE),
(22, 1, 8, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah tabung berjari-jari $7\\text{ cm}$ dan tinggi $10\\text{ cm}$. Gunakan $\\pi = \\frac{22}{7}$. Volumenya adalah ….', NULL, TRUE),
(23, 1, 9, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Data nilai: $6, 7, 7, 8, 9$. Modus data tersebut adalah ….', NULL, TRUE),
(24, 1, 9, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Rata-rata dari $4, 6, 8$, dan $x$ adalah $7$. Nilai $x$ adalah ….', NULL, TRUE),
(25, 1, 9, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Data pengunjung perpustakaan Senin hingga Kamis berturut-turut $20, 25, 15$, dan $30$ orang. Jumlah pengunjung selama empat hari adalah ….', NULL, TRUE),
(26, 1, 9, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Nilai tengah dari data terurut $3, 5, 6, 8, 10$ adalah ….', NULL, TRUE),
(27, 1, 10, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Dalam kantong ada $3$ kelereng merah, $2$ biru, dan $5$ kuning. Satu kelereng diambil acak. Pilih pernyataan benar.', NULL, TRUE),
(28, 1, 10, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Kotak berisi kartu bernomor $1$ sampai $8$. Satu kartu diambil acak. Pilih semua kejadian yang berpeluang $\\frac{1}{2}$.', NULL, TRUE),
(29, 1, 10, 3, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Di kelas ada $12$ siswa laki-laki dan $18$ siswa perempuan. Seorang siswa dipilih acak. Pilih semua kesimpulan benar.', NULL, TRUE),
(30, 1, 10, 3, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Dua dadu bersisi enam dilempar bersamaan. Pilih semua jumlah mata dadu yang peluangnya sama besar.', NULL, TRUE),
(31, 1, 1, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Manakah bilangan yang termasuk bilangan irasional?', NULL, TRUE),
(32, 1, 1, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua pernyataan yang benar tentang bilangan $-3$, $0$, dan $\\frac{5}{2}$.', NULL, TRUE),
(33, 1, 1, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua bilangan yang nilainya sama dengan $0{,}4$.', NULL, TRUE),
(34, 1, 1, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Suhu di kota P $-3^\\circ\\text{C}$. Pada siang hari suhu naik $8^\\circ\\text{C}$. Berapa suhu siang hari?', NULL, TRUE),
(35, 1, 1, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah resep membutuhkan $\\frac{3}{4}\\text{ kg}$ tepung. Jika akan membuat $2$ resep, banyak tepung yang diperlukan adalah ….', NULL, TRUE),
(36, 1, 1, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah barang berharga $\\text{Rp}80.000$ mendapat diskon $15\\%$. Harga setelah diskon adalah ….', NULL, TRUE),
(37, 1, 1, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Bak penampung berisi $2{,}4\\text{ liter}$ air. Lalu dituangkan $\\frac{3}{5}\\text{ liter}$ ke gelas dan ditambah $450\\text{ mL}$ air. Berapa banyak air di bak sekarang?', NULL, TRUE),
(38, 1, 1, 3, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua pernyataan yang selalu benar untuk bilangan real $x$.', NULL, TRUE),
(39, 1, 2, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Jika $3x + 5 = 20$, nilai $x$ adalah ….', NULL, TRUE),
(40, 1, 2, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Panjang persegi panjang $3\\text{ cm}$ lebih dari lebarnya. Kelilingnya $30\\text{ cm}$. Lebarnya adalah ….', NULL, TRUE),
(41, 1, 3, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Diketahui $p = 2$ dan $q = -3$. Pilih semua pernyataan yang benar.', NULL, TRUE),
(42, 1, 3, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sederhanakan $2(3x - 4) - (x + 5)$.', NULL, TRUE),
(43, 1, 4, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Fungsi $g(x) = ax + 4$ memenuhi $g(2) = 10$. Nilai $g(5)$ adalah ….', NULL, TRUE),
(44, 1, 4, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Diberikan fungsi $h(x) = x^2$. Pilih semua pernyataan yang benar.', NULL, TRUE),
(45, 1, 5, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Tiga suku berikutnya dari barisan $4, 7, 10, 13, \\dots$ adalah ….', NULL, TRUE),
(46, 1, 6, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Dua garis sejajar dipotong sebuah garis. Jika salah satu sudut sehadap $112^\\circ$, sudut sehadap pasangannya adalah ….', NULL, TRUE),
(47, 1, 6, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua bangun yang memiliki tepat $4$ sisi.', NULL, TRUE),
(48, 1, 7, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Titik $P(2, -3)$ dicerminkan terhadap sumbu-$x$. Bayangan titik $P$ adalah ….', NULL, TRUE),
(49, 1, 7, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Titik $A(-1, 4)$ ditranslasikan oleh $T(3, -2)$. Pilih pernyataan benar.', NULL, TRUE),
(50, 1, 7, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Titik $(-2, 5)$ diputar $180^\\circ$ terhadap pusat $O(0, 0)$. Koordinat bayangannya adalah ….', NULL, TRUE),
(51, 1, 8, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Luas persegi panjang berukuran $8\\text{ cm} \\times 5\\text{ cm}$ adalah ….', NULL, TRUE),
(52, 1, 8, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Sebuah taman berbentuk persegi panjang berukuran $12\\text{ m} \\times 7\\text{ m}$. Pilih semua pernyataan benar.', NULL, TRUE),
(53, 1, 8, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah kubus memiliki panjang rusuk $4\\text{ cm}$. Volume dan luas permukaannya berturut-turut adalah ….', NULL, TRUE),
(54, 1, 9, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Data banyak buku yang dibaca lima siswa adalah $2, 4, 3, 5$, dan $6$. Pilih semua pernyataan benar.', NULL, TRUE),
(55, 1, 9, 1, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Pilih semua pernyataan yang benar tentang diagram batang.', NULL, TRUE),
(56, 1, 9, 3, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Nilai ulangan adalah $70, 75, 80, 85$. Satu nilai ditambahkan dan rata-rata lima nilai menjadi $80$. Pilih semua pernyataan benar.', NULL, TRUE),
(57, 1, 9, 2, NULL, 'SIMULATION', 'COMPLEX_CHOICE', 'Diagram lingkaran menunjukkan $40\\%$ siswa memilih sepak bola, $25\\%$ memilih bulu tangkis, $20\\%$ memilih basket, dan sisanya memilih renang. Jika ada $200$ siswa, pilih pernyataan benar.', NULL, TRUE),
(58, 1, 10, 1, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah dadu bersisi enam dilempar sekali. Peluang muncul angka genap adalah ….', NULL, TRUE),
(59, 1, 10, 3, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Sebuah koin dilempar dua kali. Peluang muncul tepat satu gambar adalah ….', NULL, TRUE),
(60, 1, 10, 2, NULL, 'SIMULATION', 'SINGLE_CHOICE', 'Roda putar dibagi menjadi $8$ bagian sama besar: $3$ merah, $2$ biru, dan $3$ hijau. Peluang jarum berhenti di warna biru adalah ….', NULL, TRUE);

-- -----------------------------------------------------------------------------
-- 3. PEMBENIHAN PILIHAN JAWABAN (QUESTION_OPTIONS - 240 Opsi A-D)
-- -----------------------------------------------------------------------------
INSERT INTO `question_options` (`id`, `question_id`, `option_label`, `option_text`, `is_correct`) VALUES
(1, 1, 'A', '$-2$, $-\\frac{1}{2}$, $0$, $1{,}5$', TRUE),
(2, 1, 'B', '$-\\frac{1}{2}$, $-2$, $0$, $1{,}5$', FALSE),
(3, 1, 'C', '$0$, $-2$, $-\\frac{1}{2}$, $1{,}5$', FALSE),
(4, 1, 'D', '$-2$, $0$, $-\\frac{1}{2}$, $1{,}5$', FALSE),
(5, 2, 'A', '$-8$', FALSE),
(6, 2, 'B', '$0$', FALSE),
(7, 2, 'C', '$8$', TRUE),
(8, 2, 'D', '$16$', FALSE),
(9, 3, 'A', 'Sisa pita setelah dipakai adalah $2{,}35\\text{ m}$', TRUE),
(10, 3, 'B', 'Setelah membeli, pita Rina berjumlah $3{,}15\\text{ m}$', TRUE),
(11, 3, 'C', 'Setelah membeli, pita Rina berjumlah $3{,}25\\text{ m}$', FALSE),
(12, 3, 'D', 'Panjang pita awal sama dengan $300\\text{ cm}$', FALSE),
(13, 4, 'A', '$\\sqrt{50}$, karena $50$ lebih besar dari $49$', TRUE),
(14, 4, 'B', '$7$, karena $7$ lebih besar dari $5$', FALSE),
(15, 4, 'C', 'Keduanya sama', FALSE),
(16, 4, 'D', 'Tidak dapat dibandingkan', FALSE),
(17, 5, 'A', '$-7$', FALSE),
(18, 5, 'B', '$-6$', FALSE),
(19, 5, 'C', '$0$', TRUE),
(20, 5, 'D', '$4$', FALSE),
(21, 6, 'A', '$\\frac{5}{8}$', FALSE),
(22, 6, 'B', '$\\frac{2}{3}$', TRUE),
(23, 6, 'C', '$\\frac{3}{5}$', FALSE),
(24, 6, 'D', 'Ketiganya sama', FALSE),
(25, 7, 'A', '$x^2 > 1$', TRUE),
(26, 7, 'B', '$x + 3 > 5$', FALSE),
(27, 7, 'C', '$\\frac{1}{x} > 1$', FALSE),
(28, 7, 'D', '$2x$ berada di antara $2$ dan $4$', TRUE),
(29, 8, 'A', 'Jika harga satu buku $x$, modelnya $3x + 4.000 = 25.000$', TRUE),
(30, 8, 'B', 'Harga satu buku $\\text{Rp}7.000$', TRUE),
(31, 8, 'C', 'Harga satu buku $\\text{Rp}9.000$', FALSE),
(32, 8, 'D', 'Modelnya $x + 4.000 = 25.000$', FALSE),
(33, 9, 'A', '$-1$', TRUE),
(34, 9, 'B', '$0$', TRUE),
(35, 9, 'C', '$5$', FALSE),
(36, 9, 'D', '$4$', FALSE),
(37, 10, 'A', '$7a - 2$', TRUE),
(38, 10, 'B', '$7a + 2$', FALSE),
(39, 10, 'C', '$5a$', FALSE),
(40, 10, 'D', '$9a - 2$', FALSE),
(41, 11, 'A', '$4 + x + 2.000$', FALSE),
(42, 11, 'B', '$4x + 2.000$', TRUE),
(43, 11, 'C', '$4(x + 2.000)$', FALSE),
(44, 11, 'D', '$x + 8.000$', FALSE),
(45, 12, 'A', '$5$', FALSE),
(46, 12, 'B', '$6$', FALSE),
(47, 12, 'C', '$7$', TRUE),
(48, 12, 'D', '$9$', FALSE),
(49, 13, 'A', '$x = 0$ menghasilkan $-2$', TRUE),
(50, 13, 'B', '$x = 1$ menghasilkan $1$', TRUE),
(51, 13, 'C', '$x = 2$ menghasilkan $5$', FALSE),
(52, 13, 'D', '$x = -1$ menghasilkan $1$', FALSE),
(53, 14, 'A', 'Tabungan minggu ke-$2$ $\\text{Rp}7.000$', TRUE),
(54, 14, 'B', 'Tabungan minggu ke-$3$ $\\text{Rp}9.000$', TRUE),
(55, 14, 'C', 'Tabungan minggu ke-$4$ $\\text{Rp}12.000$', FALSE),
(56, 14, 'D', 'Jumlah tabungan selama $4$ minggu $\\text{Rp}30.000$', FALSE),
(57, 15, 'A', '$162$', FALSE),
(58, 15, 'B', '$324$', FALSE),
(59, 15, 'C', '$486$', TRUE),
(60, 15, 'D', '$648$', FALSE),
(61, 16, 'A', '$90^\\circ$', FALSE),
(62, 16, 'B', '$180^\\circ$', TRUE),
(63, 16, 'C', '$270^\\circ$', FALSE),
(64, 16, 'D', '$360^\\circ$', FALSE),
(65, 17, 'A', 'Sudut ketiga $65^\\circ$', TRUE),
(66, 17, 'B', 'Segitiga itu lancip', TRUE),
(67, 17, 'C', 'Jumlah dua sudut yang diketahui $125^\\circ$', FALSE),
(68, 17, 'D', 'Sudut ketiga $75^\\circ$', FALSE),
(69, 18, 'A', '$18\\text{ cm}$', FALSE),
(70, 18, 'B', '$27\\text{ cm}$', FALSE),
(71, 18, 'C', '$36\\text{ cm}$', TRUE),
(72, 18, 'D', '$81\\text{ cm}$', FALSE),
(73, 19, 'A', 'Translasi', TRUE),
(74, 19, 'B', 'Rotasi', TRUE),
(75, 19, 'C', 'Dilatasi faktor $2$', FALSE),
(76, 19, 'D', 'Dilatasi faktor $0{,}5$', FALSE),
(77, 20, 'A', '$(1, -1)$', FALSE),
(78, 20, 'B', '$(-1, 1)$', TRUE),
(79, 20, 'C', '$(-1, -1)$', FALSE),
(80, 20, 'D', '$(1, 1)$', FALSE),
(81, 21, 'A', '$2{,}5\\text{ m} = 250\\text{ cm}$', TRUE),
(82, 21, 'B', '$1{,}2\\text{ kg} = 1.200\\text{ g}$', TRUE),
(83, 21, 'C', '$3\\text{ jam} = 120\\text{ menit}$', FALSE),
(84, 21, 'D', '$450\\text{ cm} = 45\\text{ m}$', FALSE),
(85, 22, 'A', '$440\\text{ cm}^3$', FALSE),
(86, 22, 'B', '$1.540\\text{ cm}^3$', TRUE),
(87, 22, 'C', '$3.080\\text{ cm}^3$', FALSE),
(88, 22, 'D', '$4.400\\text{ cm}^3$', FALSE),
(89, 23, 'A', '$6$', FALSE),
(90, 23, 'B', '$7$', TRUE),
(91, 23, 'C', '$8$', FALSE),
(92, 23, 'D', '$9$', FALSE),
(93, 24, 'A', '$8$', FALSE),
(94, 24, 'B', '$9$', FALSE),
(95, 24, 'C', '$10$', TRUE),
(96, 24, 'D', '$12$', FALSE),
(97, 25, 'A', '$75\\text{ orang}$', FALSE),
(98, 25, 'B', '$80\\text{ orang}$', FALSE),
(99, 25, 'C', '$90\\text{ orang}$', TRUE),
(100, 25, 'D', '$100\\text{ orang}$', FALSE),
(101, 26, 'A', '$5$', FALSE),
(102, 26, 'B', '$6$', TRUE),
(103, 26, 'C', '$7$', FALSE),
(104, 26, 'D', '$8$', FALSE),
(105, 27, 'A', 'Peluang mengambil merah adalah $\\frac{3}{10}$', TRUE),
(106, 27, 'B', 'Peluang mengambil biru adalah $\\frac{1}{5}$', TRUE),
(107, 27, 'C', 'Peluang mengambil kuning adalah $\\frac{3}{5}$', FALSE),
(108, 27, 'D', 'Peluang mengambil bukan kuning adalah $\\frac{2}{5}$', FALSE),
(109, 28, 'A', 'Mendapat angka ganjil', TRUE),
(110, 28, 'B', 'Mendapat angka lebih dari $4$', TRUE),
(111, 28, 'C', 'Mendapat angka prima yang lebih dari $3$', FALSE),
(112, 28, 'D', 'Mendapat angka kurang dari $4$', FALSE),
(113, 29, 'A', 'Peluang terpilih siswa perempuan adalah $\\frac{3}{5}$', TRUE),
(114, 29, 'B', 'Peluang terpilih siswa laki-laki adalah $\\frac{2}{5}$', TRUE),
(115, 29, 'C', 'Peluang terpilih bukan laki-laki adalah $\\frac{1}{2}$', FALSE),
(116, 29, 'D', 'Siswa laki-laki lebih mungkin terpilih daripada perempuan', FALSE),
(117, 30, 'A', 'Jumlah $2$', TRUE),
(118, 30, 'B', 'Jumlah $3$', FALSE),
(119, 30, 'C', 'Jumlah $7$', FALSE),
(120, 30, 'D', 'Jumlah $12$', TRUE),
(121, 31, 'A', '$0{,}75$', FALSE),
(122, 31, 'B', '$\\sqrt{49}$', FALSE),
(123, 31, 'C', '$\\sqrt{18}$', TRUE),
(124, 31, 'D', '$-4$', FALSE),
(125, 32, 'A', '$-3$ adalah bilangan bulat', TRUE),
(126, 32, 'B', '$0$ bukan bilangan rasional', FALSE),
(127, 32, 'C', '$\\frac{5}{2}$ adalah bilangan rasional', TRUE),
(128, 32, 'D', 'Ketiganya bilangan irasional', FALSE),
(129, 33, 'A', '$\\frac{2}{5}$', TRUE),
(130, 33, 'B', '$40\\%$', TRUE),
(131, 33, 'C', '$\\frac{4}{100}$', FALSE),
(132, 33, 'D', '$0{,}04$', FALSE),
(133, 34, 'A', '$-11^\\circ\\text{C}$', FALSE),
(134, 34, 'B', '$-5^\\circ\\text{C}$', FALSE),
(135, 34, 'C', '$5^\\circ\\text{C}$', TRUE),
(136, 34, 'D', '$11^\\circ\\text{C}$', FALSE),
(137, 35, 'A', '$1\\frac{1}{4}\\text{ kg}$', FALSE),
(138, 35, 'B', '$1\\frac{1}{2}\\text{ kg}$', TRUE),
(139, 35, 'C', '$2\\frac{1}{4}\\text{ kg}$', FALSE),
(140, 35, 'D', '$3\\text{ kg}$', FALSE),
(141, 36, 'A', '$\\text{Rp}12.000$', FALSE),
(142, 36, 'B', '$\\text{Rp}65.000$', FALSE),
(143, 36, 'C', '$\\text{Rp}68.000$', TRUE),
(144, 36, 'D', '$\\text{Rp}92.000$', FALSE),
(145, 37, 'A', '$1{,}8\\text{ liter}$', FALSE),
(146, 37, 'B', '$2{,}1\\text{ liter}$', FALSE),
(147, 37, 'C', '$2{,}25\\text{ liter}$', TRUE),
(148, 37, 'D', '$2{,}85\\text{ liter}$', FALSE),
(149, 38, 'A', '$|x| \\ge 0$', TRUE),
(150, 38, 'B', '$x^2 \\ge 0$', TRUE),
(151, 38, 'C', 'Jika $x < 0$, maka $|x| = x$', FALSE),
(152, 38, 'D', 'Jika $x = -a$ dengan $a > 0$, maka $|x| = -a$', FALSE),
(153, 39, 'A', '$3$', FALSE),
(154, 39, 'B', '$5$', TRUE),
(155, 39, 'C', '$7$', FALSE),
(156, 39, 'D', '$25$', FALSE),
(157, 40, 'A', '$5\\text{ cm}$', FALSE),
(158, 40, 'B', '$6\\text{ cm}$', TRUE),
(159, 40, 'C', '$9\\text{ cm}$', FALSE),
(160, 40, 'D', '$12\\text{ cm}$', FALSE),
(161, 41, 'A', '$p + q = -1$', TRUE),
(162, 41, 'B', '$2p - q = 1$', FALSE),
(163, 41, 'C', '$pq = -6$', TRUE),
(164, 41, 'D', '$p^2 + q = 5$', FALSE),
(165, 42, 'A', '$5x - 13$', TRUE),
(166, 42, 'B', '$5x - 3$', FALSE),
(167, 42, 'C', '$7x - 13$', FALSE),
(168, 42, 'D', '$7x - 3$', FALSE),
(169, 43, 'A', '$13$', FALSE),
(170, 43, 'B', '$16$', FALSE),
(171, 43, 'C', '$19$', TRUE),
(172, 43, 'D', '$29$', FALSE),
(173, 44, 'A', '$h(-2) = 4$', TRUE),
(174, 44, 'B', '$h(0) = 0$', TRUE),
(175, 44, 'C', '$h(3) = 6$', FALSE),
(176, 44, 'D', '$h(1) = 2$', FALSE),
(177, 45, 'A', '$14, 15, 16$', FALSE),
(178, 45, 'B', '$16, 19, 22$', TRUE),
(179, 45, 'C', '$15, 18, 21$', FALSE),
(180, 45, 'D', '$17, 21, 25$', FALSE),
(181, 46, 'A', '$68^\\circ$', FALSE),
(182, 46, 'B', '$78^\\circ$', FALSE),
(183, 46, 'C', '$112^\\circ$', TRUE),
(184, 46, 'D', '$180^\\circ$', FALSE),
(185, 47, 'A', 'Persegi', TRUE),
(186, 47, 'B', 'Segitiga', FALSE),
(187, 47, 'C', 'Trapesium', TRUE),
(188, 47, 'D', 'Segi lima', FALSE),
(189, 48, 'A', '$(-2, -3)$', FALSE),
(190, 48, 'B', '$(2, 3)$', TRUE),
(191, 48, 'C', '$(-2, 3)$', FALSE),
(192, 48, 'D', '$(3, 2)$', FALSE),
(193, 49, 'A', 'Koordinat $x$ bayangan adalah $2$', TRUE),
(194, 49, 'B', 'Koordinat $y$ bayangan adalah $2$', TRUE),
(195, 49, 'C', 'Bayangan $A$ adalah $(2, -2)$', FALSE),
(196, 49, 'D', 'Jarak titik ke bayangannya $5$ satuan', FALSE),
(197, 50, 'A', '$(2, -5)$', TRUE),
(198, 50, 'B', '$(-5, 2)$', FALSE),
(199, 50, 'C', '$(2, 5)$', FALSE),
(200, 50, 'D', '$(-2, -5)$', FALSE),
(201, 51, 'A', '$13\\text{ cm}^2$', FALSE),
(202, 51, 'B', '$26\\text{ cm}^2$', FALSE),
(203, 51, 'C', '$40\\text{ cm}^2$', TRUE),
(204, 51, 'D', '$80\\text{ cm}^2$', FALSE),
(205, 52, 'A', 'Luasnya $84\\text{ m}^2$', TRUE),
(206, 52, 'B', 'Kelilingnya $38\\text{ m}$', TRUE),
(207, 52, 'C', 'Panjang pagar satu putaran $76\\text{ m}$', FALSE),
(208, 52, 'D', 'Luasnya $19\\text{ m}^2$', FALSE),
(209, 53, 'A', '$16\\text{ cm}^3$ dan $64\\text{ cm}^2$', FALSE),
(210, 53, 'B', '$64\\text{ cm}^3$ dan $96\\text{ cm}^2$', TRUE),
(211, 53, 'C', '$64\\text{ cm}^3$ dan $16\\text{ cm}^2$', FALSE),
(212, 53, 'D', '$96\\text{ cm}^3$ dan $64\\text{ cm}^2$', FALSE),
(213, 54, 'A', 'Rata-ratanya $4$', TRUE),
(214, 54, 'B', 'Mediannya $4$', TRUE),
(215, 54, 'C', 'Jangkauannya $5$', FALSE),
(216, 54, 'D', 'Modusnya $3$', FALSE),
(217, 55, 'A', 'Tinggi batang dapat menunjukkan banyak data', TRUE),
(218, 55, 'B', 'Setiap batang harus selalu memiliki tinggi sama', FALSE),
(219, 55, 'C', 'Kategori biasanya ditulis pada sumbu mendatar', TRUE),
(220, 55, 'D', 'Diagram batang tidak dapat digunakan untuk membandingkan data', FALSE),
(221, 56, 'A', 'Jumlah lima nilai adalah $400$', TRUE),
(222, 56, 'B', 'Nilai tambahan adalah $90$', TRUE),
(223, 56, 'C', 'Nilai tambahan lebih kecil daripada nilai tertinggi sebelumnya', FALSE),
(224, 56, 'D', 'Median lima nilai adalah $85$', FALSE),
(225, 57, 'A', '$80$ siswa memilih sepak bola', TRUE),
(226, 57, 'B', '$50$ siswa memilih bulu tangkis', TRUE),
(227, 57, 'C', '$40$ siswa memilih renang', FALSE),
(228, 57, 'D', '$50$ siswa memilih basket', FALSE),
(229, 58, 'A', '$\\frac{1}{6}$', FALSE),
(230, 58, 'B', '$\\frac{1}{3}$', FALSE),
(231, 58, 'C', '$\\frac{1}{2}$', TRUE),
(232, 58, 'D', '$\\frac{2}{3}$', FALSE),
(233, 59, 'A', '$\\frac{1}{4}$', FALSE),
(234, 59, 'B', '$\\frac{1}{2}$', TRUE),
(235, 59, 'C', '$\\frac{3}{4}$', FALSE),
(236, 59, 'D', '$1$', FALSE),
(237, 60, 'A', '$\\frac{1}{8}$', FALSE),
(238, 60, 'B', '$\\frac{1}{4}$', TRUE),
(239, 60, 'C', '$\\frac{3}{8}$', FALSE),
(240, 60, 'D', 'Peluang jarum berhenti di warna biru adalah $\\frac{1}{2}$', FALSE);

-- -----------------------------------------------------------------------------
-- 4. PEMBENIHAN PEMBAHASAN SOAL (QUESTION_EXPLANATIONS - 60 Pembahasan)
-- -----------------------------------------------------------------------------
INSERT INTO `question_explanations` (`id`, `question_id`, `explanation_text`, `reasoning_guide`, `reference_url`) VALUES
(1, 1, 'Pada garis bilangan, bilangan yang lebih ke kiri nilainya lebih kecil. Di antara bilangan negatif, $-2$ lebih kecil daripada $-\\frac{1}{2}$. Setelah itu ada $0$, lalu $1{,}5$. Maka urutan A yang benar.', NULL, NULL),
(2, 2, 'Nilai mutlak menunjukkan jarak suatu bilangan dari nol, sehingga hasilnya tidak negatif. Jarak $-8$ ke $0$ adalah $8$ satuan. Jadi $|-8| = 8$.', NULL, NULL),
(3, 3, 'Pita setelah dipakai: $3{,}6 - 1{,}25 = 2{,}35\\text{ m}$. Setelah membeli lagi: $2{,}35 + 0{,}8 = 3{,}15\\text{ m}$. Pernyataan A dan B benar. Pernyataan C salah karena hasil perhitungannya $3{,}15\\text{ m}$, dan pernyataan D salah karena panjang pita awal $3{,}6\\text{ m}$ sama dengan $360\\text{ cm}$, bukan $300\\text{ cm}$.', NULL, NULL),
(4, 4, 'Karena kedua bilangan positif, kita boleh membandingkan kuadratnya. $7^2 = 49$, sedangkan $50 > 49$, jadi $\\sqrt{50} > \\sqrt{49} = 7$. Pilihan A benar.', NULL, NULL),
(5, 5, 'Kalikan semua bagian pertidaksamaan dengan $3$ (tandanya tetap karena $3$ positif): $-6 < n < 3$. Bilangan bulat yang memenuhi ialah $-5$ sampai $2$. Dari pilihan yang tersedia, hanya $0$ yang termasuk.', NULL, NULL),
(6, 6, 'Samakan penyebut menjadi $120$: $\\frac{5}{8} = \\frac{75}{120}$, $\\frac{2}{3} = \\frac{80}{120}$, dan $\\frac{3}{5} = \\frac{72}{120}$. Pembilang terbesar adalah $80$, sehingga $\\frac{2}{3}$ merupakan pecahan terbesar.', NULL, NULL),
(7, 7, 'Karena $1 < x < 2$, menguadratkan kedua ruas menghasilkan $1 < x^2 < 4$, sehingga $x^2 > 1$ (A benar). Menambahkan $3$ menghasilkan $4 < x + 3 < 5$, sehingga $x + 3 < 5$ (B salah). Membagi $1$ dengan $x$ menghasilkan $\\frac{1}{2} < \\frac{1}{x} < 1$ (C salah). Mengalikan dengan $2$ menghasilkan $2 < 2x < 4$ (D benar). Jadi kesimpulan yang benar adalah A dan D.', NULL, NULL),
(8, 8, 'Misalkan harga satu buku $x$ rupiah. Tiga buku dan satu pensil menghasilkan $3x + 4.000 = 25.000$. Kurangi $4.000$, didapat $3x = 21.000$, sehingga $x = 7.000$. Maka A dan B benar.', NULL, NULL),
(9, 9, 'Selesaikan pertidaksamaan $2x - 1 \\le 5$ dengan menambahkan $1$ pada kedua ruas menjadi $2x \\le 6$, lalu bagi dengan $2$ sehingga diperoleh $x \\le 3$. Dari pilihan yang tersedia, $-1$ dan $0$ memenuhi pertidaksamaan tersebut, sedangkan $5$ dan $4$ tidak memenuhi karena lebih besar dari $3$. Jadi pilihan yang benar adalah A dan B.', NULL, NULL),
(10, 10, 'Suku sejenis yang memuat $a$ dapat dijumlahkan: $4a + 3a = 7a$. Bilangan $-2$ tetap karena bukan suku sejenis dengan $a$. Jadi bentuk sederhananya $7a - 2$.', NULL, NULL),
(11, 11, 'Empat roti berharga $4$ kali harga satu roti, yaitu $4x$. Biaya kantong ditambahkan sekali, jadi totalnya $4x + 2.000$. Pilihan B memodelkan situasi dengan benar.', NULL, NULL),
(12, 12, '$f(3)$ berarti mengganti setiap $x$ dengan $3$: $f(3) = 2(3) + 1 = 6 + 1 = 7$. Jadi jawabannya C.', NULL, NULL),
(13, 13, 'Masukkan nilai ke aturan $3x - 2$. Untuk $x = 0$ hasilnya $-2$; $x = 1$ hasilnya $1$; $x = 2$ hasilnya $4$ (bukan $5$); dan $x = -1$ hasilnya $-5$ (bukan $1$). Jadi A dan B benar.', NULL, NULL),
(14, 14, 'Tabungan membentuk barisan aritmetika: minggu ke-$1$ = $\\text{Rp}5.000$, minggu ke-$2$ = $\\text{Rp}5.000 + \\text{Rp}2.000 = \\text{Rp}7.000$, minggu ke-$3$ = $\\text{Rp}7.000 + \\text{Rp}2.000 = \\text{Rp}9.000$, dan minggu ke-$4$ = $\\text{Rp}9.000 + \\text{Rp}2.000 = \\text{Rp}11.000$ (C salah). Jumlah tabungan selama $4$ minggu = $5.000 + 7.000 + 9.000 + 11.000 = \\text{Rp}32.000$ (D salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(15, 15, 'Setiap suku dikalikan $3$: suku ke-$5$ = $54 \\times 3 = 162$ dan suku ke-$6$ = $162 \\times 3 = 486$. Jadi pilihan C benar.', NULL, NULL),
(16, 16, 'Ketiga sudut dalam segitiga selalu berjumlah $180^\\circ$. Misalnya, jika dua sudutnya diketahui, sudut ketiga diperoleh dengan mengurangi jumlah $180^\\circ$ dengan dua sudut tersebut.', NULL, NULL),
(17, 17, 'Sudut ketiga segitiga = $180^\\circ - 48^\\circ - 67^\\circ = 65^\\circ$. Karena ketiga sudutnya ($48^\\circ, 67^\\circ, 65^\\circ$) semuanya kurang dari $90^\\circ$, segitiga tersebut merupakan segitiga lancip. Jumlah dua sudut yang diketahui adalah $48^\\circ + 67^\\circ = 115^\\circ$. Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(18, 18, 'Keliling persegi adalah $4$ kali panjang sisinya. Jadi $4 \\times 9 = 36\\text{ cm}$. Nilai $81\\text{ cm}^2$ adalah luasnya, bukan kelilingnya.', NULL, NULL),
(19, 19, 'Translasi dan rotasi merupakan jenis transformasi isometri yang mempertahankan bentuk dan ukuran bangun. Sebaliknya, dilatasi dengan faktor skala selain $1$ (seperti faktor $2$ maupun faktor $0{,}5$) akan mengubah ukuran bangun. Jadi transformasi yang benar adalah A dan B.', NULL, NULL),
(20, 20, 'Pencerminan terhadap sumbu-$y$ mengubah $(x, y)$ menjadi $(-x, y)$. Maka $A(1, 1)$ menjadi $A\'(-1, 1)$.', NULL, NULL),
(21, 21, 'Konversi yang tepat: $1\\text{ m} = 100\\text{ cm}$, sehingga $2{,}5\\text{ m} = 250\\text{ cm}$ (A benar). $1\\text{ kg} = 1.000\\text{ g}$, sehingga $1{,}2\\text{ kg} = 1.200\\text{ g}$ (B benar). $1\\text{ jam} = 60\\text{ menit}$, sehingga $3\\text{ jam} = 180\\text{ menit}$ (C salah). $450\\text{ cm} = 4{,}5\\text{ m}$, bukan $45\\text{ m}$ (D salah). Jadi konversi yang benar adalah A dan B.', NULL, NULL),
(22, 22, 'Volume tabung = $\\pi r^2 t$. Masukkan nilai: $\\frac{22}{7} \\times 7^2 \\times 10 = 22 \\times 7 \\times 10 = 1.540\\text{ cm}^3$. Jadi jawabannya B.', NULL, NULL),
(23, 23, 'Modus adalah nilai yang paling sering muncul. Nilai $7$ muncul dua kali, sementara nilai lain hanya sekali. Jadi modusnya $7$.', NULL, NULL),
(24, 24, 'Empat data dengan rata-rata $7$ memiliki jumlah $4 \\times 7 = 28$. Tiga data yang diketahui berjumlah $4 + 6 + 8 = 18$. Jadi $x = 28 - 18 = 10$.', NULL, NULL),
(25, 25, 'Jumlahkan semua data: $20 + 25 + 15 + 30 = 90$. Jadi jumlah pengunjung selama empat hari adalah $90$ orang.', NULL, NULL),
(26, 26, 'Ada lima data, jadi median adalah data yang berada tepat di posisi ketiga setelah diurutkan. Data ketiga adalah $6$.', NULL, NULL),
(27, 27, 'Total kelereng = $3 + 2 + 5 = 10$. Peluang merah = $\\frac{3}{10}$ (A benar). Peluang biru = $\\frac{2}{10} = \\frac{1}{5}$ (B benar). Peluang kuning = $\\frac{5}{10} = \\frac{1}{2}$ (C salah). Peluang bukan kuning = $\\frac{5}{10} = \\frac{1}{2}$ (D salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(28, 28, 'Ada $8$ kartu ($1$ sampai $8$). Angka ganjil ada $4$ ($1, 3, 5, 7$) dengan peluang $\\frac{4}{8} = \\frac{1}{2}$ (A benar). Angka lebih dari $4$ ada $4$ ($5, 6, 7, 8$) dengan peluang $\\frac{4}{8} = \\frac{1}{2}$ (B benar). Angka prima lebih dari $3$ hanya $5$ dan $7$ (peluang $\\frac{2}{8} = \\frac{1}{4}$, C salah). Angka kurang dari $4$ ada $3$ ($1, 2, 3$) dengan peluang $\\frac{3}{8}$ (D salah). Jadi kejadian yang berpeluang $\\frac{1}{2}$ adalah A dan B.', NULL, NULL),
(29, 29, 'Jumlah seluruh siswa = $12 + 18 = 30$ siswa. Peluang terpilih siswa perempuan = $\\frac{18}{30} = \\frac{3}{5}$ (A benar). Peluang terpilih siswa laki-laki = $\\frac{12}{30} = \\frac{2}{5}$ (B benar). Pilihan C salah karena peluang bukan laki-laki sama dengan peluang perempuan yaitu $\\frac{3}{5}$. Pilihan D salah karena siswa perempuan ($18$ siswa) lebih banyak daripada siswa laki-laki ($12$ siswa). Jadi jawaban yang benar adalah A dan B.', NULL, NULL),
(30, 30, 'Ada $36$ pasangan hasil yang sama mungkin. Jumlah $2$ hanya terjadi sebagai $(1, 1)$, sedangkan jumlah $12$ hanya sebagai $(6, 6)$, jadi masing-masing berpeluang $\\frac{1}{36}$. Jumlah $3$ memiliki dua pasangan, dan jumlah $7$ memiliki enam pasangan. Karena itu A dan D benar.', NULL, NULL),
(31, 31, 'Bilangan irasional tidak dapat ditulis sebagai pecahan dua bilangan bulat. $\\sqrt{18} = 3\\sqrt{2}$, dan $\\sqrt{2}$ tidak dapat dinyatakan sebagai pecahan tepat. Sementara itu, $0{,}75 = \\frac{3}{4}$, $\\sqrt{49} = 7$, dan $-4$ semuanya rasional.', NULL, NULL),
(32, 32, 'Bilangan bulat mencakup bilangan negatif, nol, dan positif tanpa bagian pecahan, jadi $-3$ termasuk bilangan bulat. Bilangan $0$ rasional karena dapat ditulis $\\frac{0}{1}$. Demikian pula $\\frac{5}{2}$ sudah berbentuk perbandingan dua bilangan bulat. Jadi A dan C benar.', NULL, NULL),
(33, 33, 'Konversi ke bentuk desimal: $\\frac{2}{5} = 0{,}4$ (A benar) dan $40\\% = \\frac{40}{100} = 0{,}4$ (B benar). Sedangkan $\\frac{4}{100} = 0{,}04$ (C salah) dan $0{,}04 \\ne 0{,}4$ (D salah). Jadi bilangan yang nilainya sama dengan $0{,}4$ adalah A dan B.', NULL, NULL),
(34, 34, 'Kenaikan suhu berarti menambahkan $8$ pada suhu awal: $-3 + 8 = 5$. Kita dapat membayangkan mulai dari $-3$ lalu bergerak $8$ langkah ke kanan pada garis bilangan. Suhu siang hari adalah $5^\\circ\\text{C}$.', NULL, NULL),
(35, 35, 'Dua resep berarti kebutuhan dikalikan $2$: $2 \\times \\frac{3}{4} = \\frac{6}{4} = \\frac{3}{2} = 1\\frac{1}{2}\\text{ kg}$. Jadi pilihan B tepat.', NULL, NULL),
(36, 36, 'Diskon $15\\%$ dari $\\text{Rp}80.000$ adalah $0{,}15 \\times 80.000 = \\text{Rp}12.000$. Harga yang dibayar = $80.000 - 12.000 = \\text{Rp}68.000$. Diskon mengurangi harga, jadi pilihan C benar.', NULL, NULL),
(37, 37, 'Ubah $\\frac{3}{5}\\text{ liter}$ menjadi $0{,}6\\text{ liter}$. Sesudah dituangkan, tersisa $2{,}4 - 0{,}6 = 1{,}8\\text{ liter}$. Tambahkan $450\\text{ mL} = 0{,}45\\text{ liter}$: $1{,}8 + 0{,}45 = 2{,}25\\text{ liter}$. Jadi jawabannya C.', NULL, NULL),
(38, 38, 'Nilai mutlak menyatakan jarak non-negatif dari nol sehingga $|x| \\ge 0$ selalu benar (A benar). Kuadrat sembarang bilangan real tidak pernah negatif sehingga $x^2 \\ge 0$ selalu benar (B benar). Untuk $x < 0$, nilai mutlaknya adalah $|x| = -x$ (C salah). Jika $x = -a$ dengan $a > 0$, maka $|x| = |-a| = a$, bukan $-a$ (D salah). Jadi pernyataan yang selalu benar adalah A dan B.', NULL, NULL),
(39, 39, 'Kurangi kedua ruas dengan $5$ sehingga $3x = 15$. Lalu bagi kedua ruas dengan $3$: $x = 5$. Substitusi kembali memberi $3(5) + 5 = 20$, cocok dengan persamaan.', NULL, NULL),
(40, 40, 'Misalkan lebar $w\\text{ cm}$, maka panjangnya $w + 3$. Keliling $2(\\text{panjang} + \\text{lebar}) = 30$, sehingga $2((w + 3) + w) = 30$. Jadi $4w + 6 = 30$, $4w = 24$, dan $w = 6\\text{ cm}$.', NULL, NULL),
(41, 41, 'Substitusi nilai $p = 2$ dan $q = -3$: $p + q = 2 + (-3) = -1$ (A benar). $2p - q = 2(2) - (-3) = 4 + 3 = 7$, bukan $1$ (B salah). $pq = 2 \\times (-3) = -6$ (C benar). $p^2 + q = 2^2 + (-3) = 4 - 3 = 1$, bukan $5$ (D salah). Jadi pernyataan yang benar adalah A dan C.', NULL, NULL),
(42, 42, 'Kalikan $2$ ke dalam kurung pertama: $6x - 8$. Tanda minus di depan kurung kedua mengubah tandanya menjadi $-x - 5$. Gabungkan suku sejenis: $6x - x = 5x$ dan $-8 - 5 = -13$. Hasilnya adalah $5x - 13$.', NULL, NULL),
(43, 43, 'Dari $g(2) = 10$ diperoleh $2a + 4 = 10$, maka $a = 3$. Jadi $g(x) = 3x + 4$ dan $g(5) = 15 + 4 = 19$. Jawaban yang benar C.', NULL, NULL),
(44, 44, 'Fungsi $h(x) = x^2$ menguadratkan setiap nilai masukan: $h(-2) = (-2)^2 = 4$ (A benar) dan $h(0) = 0^2 = 0$ (B benar). Pilihan C salah karena $h(3) = 3^2 = 9$ (bukan $6$), dan pilihan D salah karena $h(1) = 1^2 = 1$ (bukan $2$). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(45, 45, 'Selisih setiap suku adalah $3$. Tambahkan $3$ berturut-turut pada $13$: $16$, $19$, lalu $22$. Jadi pilihan B benar.', NULL, NULL),
(46, 46, 'Pada dua garis sejajar, sudut sehadap besarnya sama. Karena sudut pertama $112^\\circ$, pasangannya juga $112^\\circ$. Sudut yang berpelurus dengannya memang $68^\\circ$, tetapi yang ditanyakan sudut sehadap.', NULL, NULL),
(47, 47, 'Persegi mempunyai empat sisi. Trapesium juga segi empat, meskipun bentuk sisi sejajarnya berbeda. Segitiga punya tiga sisi dan segi lima punya lima sisi. Jadi A dan C.', NULL, NULL),
(48, 48, 'Pencerminan terhadap sumbu-$x$ mempertahankan koordinat $x$ dan mengubah tanda koordinat $y$: $(x, y)$ menjadi $(x, -y)$. Maka $P(2, -3)$ menjadi $(2, 3)$.', NULL, NULL),
(49, 49, 'Translasi titik $A(-1, 4)$ oleh $T(3, -2)$ menghasilkan titik bayangan $A\'(-1 + 3, 4 + (-2)) = (2, 2)$. Maka koordinat $x$ bayangan adalah $2$ (A benar) dan koordinat $y$ bayangan adalah $2$ (B benar). Pilihan C salah karena koordinat bayangan yang benar adalah $(2, 2)$, bukan $(2, -2)$. Pilihan D salah karena jarak pergeserannya adalah $\\sqrt{3^2 + (-2)^2} = \\sqrt{13}$ satuan. Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(50, 50, 'Rotasi $180^\\circ$ terhadap titik pusat mengubah $(x, y)$ menjadi $(-x, -y)$. Jadi $(-2, 5)$ berpindah ke $(2, -5)$.', NULL, NULL),
(51, 51, 'Luas persegi panjang = panjang $\\times$ lebar. Jadi $8 \\times 5 = 40\\text{ cm}^2$. Satuan luas memakai $\\text{cm}^2$ karena dua ukuran panjang dikalikan.', NULL, NULL),
(52, 52, 'Taman persegi panjang dengan ukuran $12\\text{ m} \\times 7\\text{ m}$ memiliki luas = $12 \\times 7 = 84\\text{ m}^2$ (A benar). Keliling taman = $2 \\times (12 + 7) = 2 \\times 19 = 38\\text{ m}$ (B benar). Panjang pagar satu putaran sama dengan kelilingnya yaitu $38\\text{ m}$, bukan $76\\text{ m}$ (C salah). Luasnya $84\\text{ m}^2$, bukan $19\\text{ m}^2$ (D salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(53, 53, 'Volume kubus = $s^3 = 4^3 = 64\\text{ cm}^3$. Luas permukaan = $6s^2 = 6 \\times 16 = 96\\text{ cm}^2$. Jadi pasangan yang tepat adalah pilihan B.', NULL, NULL),
(54, 54, 'Data setelah diurutkan: $2, 3, 4, 5, 6$. Rata-rata = $\\frac{2 + 3 + 4 + 5 + 6}{5} = \\frac{20}{5} = 4$ (A benar). Median (nilai tengah data ke-$3$) adalah $4$ (B benar). Jangkauan = nilai terbesar $-$ nilai terkecil = $6 - 2 = 4$, bukan $5$ (C salah). Karena semua nilai muncul sekali, data tidak memiliki modus (D salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(55, 55, 'Pada diagram batang, tinggi atau panjang batang merepresentasikan frekuensi/banyak data (A benar) dan kategori umumnya diletakkan pada sumbu mendatar (C benar). Pilihan B salah karena tinggi batang bervariasi sesuai frekuensi data. Pilihan D salah karena diagram batang sangat efektif untuk membandingkan data antarkategori. Jadi pernyataan yang benar adalah A dan C.', NULL, NULL),
(56, 56, 'Agar rata-rata lima nilai menjadi $80$, jumlah kelima nilai harus $5 \\times 80 = 400$ (A benar). Empat nilai awal berjumlah $70 + 75 + 80 + 85 = 310$, sehingga nilai tambahannya adalah $400 - 310 = 90$ (B benar). Nilai tambahan ($90$) lebih besar daripada nilai tertinggi sebelumnya ($85$), sehingga C salah. Urutan lima nilai: $70, 75, 80, 85, 90$ memiliki median $80$, bukan $85$ (D salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(57, 57, 'Dari $200$ siswa: Sepak bola = $40\\% \\times 200 = 80$ siswa (A benar). Bulu tangkis = $25\\% \\times 200 = 50$ siswa (B benar). Basket = $20\\% \\times 200 = 40$ siswa (D salah). Persentase renang = $100\\% - (40\\% + 25\\% + 20\\%) = 15\\%$, sehingga banyak siswa yang memilih renang = $15\\% \\times 200 = 30$ siswa, bukan $40$ siswa (C salah). Jadi pernyataan yang benar adalah A dan B.', NULL, NULL),
(58, 58, 'Angka genap pada dadu adalah $2, 4$, dan $6$, ada $3$ hasil yang diinginkan dari $6$ hasil sama mungkin. Peluangnya $\\frac{3}{6} = \\frac{1}{2}$.', NULL, NULL),
(59, 59, 'Kemungkinan hasilnya GG, GA, AG, AA dan semuanya sama mungkin. Tepat satu gambar terjadi pada GA atau AG, yaitu $2$ dari $4$ kemungkinan. Peluangnya $\\frac{2}{4} = \\frac{1}{2}$.', NULL, NULL),
(60, 60, 'Dua dari delapan bagian berwarna biru. Peluangnya $\\frac{2}{8}$ yang disederhanakan menjadi $\\frac{1}{4}$.', NULL, NULL);

-- -----------------------------------------------------------------------------
-- 5. PEMETAAN BUTIR SOAL KE PAKET SIMULASI (SIMULATION_QUESTIONS - 60 Pemetaan)
-- -----------------------------------------------------------------------------
INSERT INTO `simulation_questions` (`id`, `simulation_id`, `question_id`, `question_order`) VALUES
(1, 1, 1, 1),
(2, 1, 2, 2),
(3, 1, 3, 3),
(4, 1, 4, 4),
(5, 1, 5, 5),
(6, 1, 6, 6),
(7, 1, 7, 7),
(8, 1, 8, 8),
(9, 1, 9, 9),
(10, 1, 10, 10),
(11, 1, 11, 11),
(12, 1, 12, 12),
(13, 1, 13, 13),
(14, 1, 14, 14),
(15, 1, 15, 15),
(16, 1, 16, 16),
(17, 1, 17, 17),
(18, 1, 18, 18),
(19, 1, 19, 19),
(20, 1, 20, 20),
(21, 1, 21, 21),
(22, 1, 22, 22),
(23, 1, 23, 23),
(24, 1, 24, 24),
(25, 1, 25, 25),
(26, 1, 26, 26),
(27, 1, 27, 27),
(28, 1, 28, 28),
(29, 1, 29, 29),
(30, 1, 30, 30),
(31, 2, 31, 1),
(32, 2, 32, 2),
(33, 2, 33, 3),
(34, 2, 34, 4),
(35, 2, 35, 5),
(36, 2, 36, 6),
(37, 2, 37, 7),
(38, 2, 38, 8),
(39, 2, 39, 9),
(40, 2, 40, 10),
(41, 2, 41, 11),
(42, 2, 42, 12),
(43, 2, 43, 13),
(44, 2, 44, 14),
(45, 2, 45, 15),
(46, 2, 46, 16),
(47, 2, 47, 17),
(48, 2, 48, 18),
(49, 2, 49, 19),
(50, 2, 50, 20),
(51, 2, 51, 21),
(52, 2, 52, 22),
(53, 2, 53, 23),
(54, 2, 54, 24),
(55, 2, 55, 25),
(56, 2, 56, 26),
(57, 2, 57, 27),
(58, 2, 58, 28),
(59, 2, 59, 29),
(60, 2, 60, 30);

SET FOREIGN_KEY_CHECKS = 1;
